[package]
name = "datalib-view-slack"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "datalib-view-slack"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.10"

[dev-dependencies]
tempfile = "3"
