[package]
name = "datalib-problems"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
name = "datalib_problems"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
datalib-etl-macros = { path = "../etl/macros" }
datalib-id = { path = "../id" }
datalib-table = { path = "../table" }
serde = { workspace = true }
sqlx = { workspace = true }
strum = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
