load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

exports_files(["Cargo.toml"])

rust_library(
    name = "datalib_whatsapp_backup",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "datalib_whatsapp_backup",
    edition = "2021",
    visibility = ["//datalib:__subpackages__"],
    deps = [
        "@datalib_crates//:aes",
        "@datalib_crates//:anyhow",
        "@datalib_crates//:cipher",
        "@datalib_crates//:ctr",
        "@datalib_crates//:flate2",
        "@datalib_crates//:ghash",
        "@datalib_crates//:hmac",
        "@datalib_crates//:md-5",
        "@datalib_crates//:sha2",
        "@datalib_crates//:subtle",
        "@datalib_crates//:thiserror",
    ],
)

rust_test(
    name = "whatsapp_backup_unittests",
    size = "small",
    crate = ":datalib_whatsapp_backup",
    edition = "2021",
    deps = [
        "@datalib_crates//:tempfile",
    ],
)
