[package]
name = "datalib-index-lib"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
name = "datalib_index_lib"
path = "src/lib.rs"

[dependencies]
datalib-schema = { path = "../schema" }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
tempfile = "3"
