-- openai_content_parts
DROP TABLE IF EXISTS `openai_content_parts`;
CREATE TABLE openai_content_parts (
    message_id    VARCHAR(64)  NOT NULL,
    part_index    INT          NOT NULL,
    kind          VARCHAR(32),
    language      VARCHAR(64),
    text          LONGTEXT,
    raw_json      JSON         NOT NULL,
    source        VARCHAR(16)  NOT NULL DEFAULT 'api',
    PRIMARY KEY (message_id, part_index)
);

INSERT INTO `openai_content_parts` (`message_id`, `part_index`, `kind`, `language`, `text`, `raw_json`, `source`) VALUES ('msg-fake-poly-0001', 0, 'text', NULL, 'Fit a degree-2 polynomial to (1,2.1),(2,4.0),(3,9.1),(4,15.8),(5,25.0) in Python.', '{"content_type":"text","value":"Fit a degree-2 polynomial to (1,2.1),(2,4.0),(3,9.1),(4,15.8),(5,25.0) in Python."}', 'api');
INSERT INTO `openai_content_parts` (`message_id`, `part_index`, `kind`, `language`, `text`, `raw_json`, `source`) VALUES ('msg-fake-poly-0002', 0, 'code', 'python', 'import numpy as np\nx = np.array([1,2,3,4,5])\ny = np.array([2.1, 4.0, 9.1, 15.8, 25.0])\ncoeffs = np.polyfit(x, y, 2)\nprint(coeffs)\n', '{"content_type":"code","language":"python","text":"import numpy as np\\nx = np.array([1,2,3,4,5])\\ny = np.array([2.1, 4.0, 9.1, 15.8, 25.0])\\ncoeffs = np.polyfit(x, y, 2)\\nprint(coeffs)\\n"}', 'api');
INSERT INTO `openai_content_parts` (`message_id`, `part_index`, `kind`, `language`, `text`, `raw_json`, `source`) VALUES ('msg-fake-poly-0003', 0, 'text', NULL, 'The fit gives approximately y = 1.014 x² + 0.06 x + 1.07. R² ≈ 0.9997. The residuals suggest the underlying process is very close to pure quadratic with small measurement noise.', '{"content_type":"text","value":"The fit gives approximately y = 1.014 x² + 0.06 x + 1.07. R² ≈ 0.9997. The residuals suggest the underlying process is very close to pure quadratic with small measurement noise."}', 'api');
INSERT INTO `openai_content_parts` (`message_id`, `part_index`, `kind`, `language`, `text`, `raw_json`, `source`) VALUES ('msg-fake-spot-0000', 0, 'model_editable_context', NULL, 'User is Lt. Cmdr. Data, a sentient android. Prefers precise, literal language.', '{"content_type":"model_editable_context","model_set_context":"User is Lt. Cmdr. Data, a sentient android. Prefers precise, literal language.","repository":null}', 'api');
INSERT INTO `openai_content_parts` (`message_id`, `part_index`, `kind`, `language`, `text`, `raw_json`, `source`) VALUES ('msg-fake-spot-0001', 0, 'text', NULL, 'Compose a Shakespearean sonnet about my cat Spot. Spot is an orange tabby with a fondness for jumping on consoles.', '{"content_type":"text","value":"Compose a Shakespearean sonnet about my cat Spot. Spot is an orange tabby with a fondness for jumping on consoles."}', 'api');
INSERT INTO `openai_content_parts` (`message_id`, `part_index`, `kind`, `language`, `text`, `raw_json`, `source`) VALUES ('msg-fake-spot-0002', 0, 'text', NULL, 'Upon the bridge, where duty bids us stand,\nA tabby of the warmest tangerine,\nWith feline grace defies the captain''s hand\nAnd treads the helm with footfall light, serene.\n\nNo Klingon foe nor anomaly arrayed\nCan match the menace of his sudden leap;\nThe console glows where Spot in mirth has played,\nAnd alarms ring out where he chose to sleep.\n\nYet Data, faithful keeper, smiles unseen —\nAn android''s joy, though circuited and spare —\nFor in this beast a mystery serene\nReflects the very life he hopes to share.\n\nSo bless thee, Spot, of fur and quiet purr:\nThou art my muse, my console saboteur.', '{"content_type":"text","value":"Upon the bridge, where duty bids us stand,\\nA tabby of the warmest tangerine,\\nWith feline grace defies the captain''s hand\\nAnd treads the helm with footfall light, serene.\\n\\nNo Klingon foe nor anomaly arrayed\\nCan match the menace of his sudden leap;\\nThe console glows where Spot in mirth has played,\\nAnd alarms ring out where he chose to sleep.\\n\\nYet Data, faithful keeper, smiles unseen —\\nAn android''s joy, though circuited and spare —\\nFor in this beast a mystery serene\\nReflects the very life he hopes to share.\\n\\nSo bless thee, Spot, of fur and quiet purr:\\nThou art my muse, my console saboteur."}', 'api');
INSERT INTO `openai_content_parts` (`message_id`, `part_index`, `kind`, `language`, `text`, `raw_json`, `source`) VALUES ('msg-fake-spot-0003', 0, 'text', NULL, 'Curious. The closing couplet is satisfying. Thank you.', '{"content_type":"text","value":"Curious. The closing couplet is satisfying. Thank you."}', 'api');
