-- openai_messages
DROP TABLE IF EXISTS `openai_messages`;
CREATE TABLE openai_messages (
    conversation_id  VARCHAR(64)  NOT NULL,
    message_id       VARCHAR(64)  NOT NULL,
    parent_id        VARCHAR(64),
    role             VARCHAR(32),
    recipient        VARCHAR(64),
    channel          VARCHAR(64),
    content_type     VARCHAR(64),
    text             LONGTEXT,
    status           VARCHAR(64),
    end_turn         BOOLEAN,
    weight           DOUBLE,
    model_slug       VARCHAR(128),
    create_time      VARCHAR(40),
    update_time      VARCHAR(40),
    raw_json         JSON         NOT NULL,
    source           VARCHAR(16)  NOT NULL DEFAULT 'api',
    last_seen_at     VARCHAR(40)  NOT NULL,
    PRIMARY KEY (message_id)
);

INSERT INTO `openai_messages` (`conversation_id`, `message_id`, `parent_id`, `role`, `recipient`, `channel`, `content_type`, `text`, `status`, `end_turn`, `weight`, `model_slug`, `create_time`, `update_time`, `raw_json`, `source`, `last_seen_at`) VALUES ('68fa0002-fake-7000-8000-positronic0002', 'msg-fake-poly-0001', 'client-created-root', 'user', 'all', NULL, 'text', 'Fit a degree-2 polynomial to (1,2.1),(2,4.0),(3,9.1),(4,15.8),(5,25.0) in Python.', 'finished_successfully', 1, 1.0, NULL, '2370-10-25T08:00:00.000000+00:00', NULL, '{"author":{"metadata":{},"name":null,"role":"user"},"channel":null,"create_time":12648470400,"end_turn":true,"id":"msg-fake-poly-0001","metadata":{},"recipient":"all","status":"finished_successfully","update_time":null,"weight":1}', 'api', '2369-04-15T00:00:00+00:00');
INSERT INTO `openai_messages` (`conversation_id`, `message_id`, `parent_id`, `role`, `recipient`, `channel`, `content_type`, `text`, `status`, `end_turn`, `weight`, `model_slug`, `create_time`, `update_time`, `raw_json`, `source`, `last_seen_at`) VALUES ('68fa0002-fake-7000-8000-positronic0002', 'msg-fake-poly-0002', 'msg-fake-poly-0001', 'assistant', 'all', 'analysis', 'code', 'import numpy as np\nx = np.array([1,2,3,4,5])\ny = np.array([2.1, 4.0, 9.1, 15.8, 25.0])\ncoeffs = np.polyfit(x, y, 2)\nprint(coeffs)\n', 'finished_successfully', 0, 1.0, 'gpt-5', '2370-10-25T08:03:20.000000+00:00', NULL, '{"author":{"metadata":{},"name":null,"role":"assistant"},"channel":"analysis","create_time":12648470600,"end_turn":false,"id":"msg-fake-poly-0002","metadata":{"model_slug":"gpt-5"},"recipient":"all","status":"finished_successfully","update_time":null,"weight":1}', 'api', '2369-04-15T00:00:00+00:00');
INSERT INTO `openai_messages` (`conversation_id`, `message_id`, `parent_id`, `role`, `recipient`, `channel`, `content_type`, `text`, `status`, `end_turn`, `weight`, `model_slug`, `create_time`, `update_time`, `raw_json`, `source`, `last_seen_at`) VALUES ('68fa0002-fake-7000-8000-positronic0002', 'msg-fake-poly-0003', 'msg-fake-poly-0002', 'assistant', 'all', 'final', 'text', 'The fit gives approximately y = 1.014 x² + 0.06 x + 1.07. R² ≈ 0.9997. The residuals suggest the underlying process is very close to pure quadratic with small measurement noise.', 'finished_successfully', 1, 1.0, 'gpt-5', '2370-10-25T08:05:20.000000+00:00', NULL, '{"author":{"metadata":{},"name":null,"role":"assistant"},"channel":"final","create_time":12648470720,"end_turn":true,"id":"msg-fake-poly-0003","metadata":{"model_slug":"gpt-5"},"recipient":"all","status":"finished_successfully","update_time":null,"weight":1}', 'api', '2369-04-15T00:00:00+00:00');
INSERT INTO `openai_messages` (`conversation_id`, `message_id`, `parent_id`, `role`, `recipient`, `channel`, `content_type`, `text`, `status`, `end_turn`, `weight`, `model_slug`, `create_time`, `update_time`, `raw_json`, `source`, `last_seen_at`) VALUES ('68fa0001-fake-7000-8000-positronic0001', 'msg-fake-spot-0000', 'client-created-root', 'system', 'all', NULL, 'model_editable_context', 'User is Lt. Cmdr. Data, a sentient android. Prefers precise, literal language.', 'finished_successfully', 1, 0.0, NULL, NULL, NULL, '{"author":{"metadata":{},"name":null,"role":"system"},"channel":null,"create_time":null,"end_turn":true,"id":"msg-fake-spot-0000","metadata":{},"recipient":"all","status":"finished_successfully","update_time":null,"weight":0}', 'api', '2369-04-15T00:00:00+00:00');
INSERT INTO `openai_messages` (`conversation_id`, `message_id`, `parent_id`, `role`, `recipient`, `channel`, `content_type`, `text`, `status`, `end_turn`, `weight`, `model_slug`, `create_time`, `update_time`, `raw_json`, `source`, `last_seen_at`) VALUES ('68fa0001-fake-7000-8000-positronic0001', 'msg-fake-spot-0001', 'msg-fake-spot-0000', 'user', 'all', NULL, 'text', 'Compose a Shakespearean sonnet about my cat Spot. Spot is an orange tabby with a fondness for jumping on consoles.', 'finished_successfully', 1, 1.0, NULL, '2370-10-24T08:00:00.000000+00:00', NULL, '{"author":{"metadata":{},"name":null,"role":"user"},"channel":null,"create_time":12648384000,"end_turn":true,"id":"msg-fake-spot-0001","metadata":{},"recipient":"all","status":"finished_successfully","update_time":null,"weight":1}', 'api', '2369-04-15T00:00:00+00:00');
INSERT INTO `openai_messages` (`conversation_id`, `message_id`, `parent_id`, `role`, `recipient`, `channel`, `content_type`, `text`, `status`, `end_turn`, `weight`, `model_slug`, `create_time`, `update_time`, `raw_json`, `source`, `last_seen_at`) VALUES ('68fa0001-fake-7000-8000-positronic0001', 'msg-fake-spot-0002', 'msg-fake-spot-0001', 'assistant', 'all', NULL, 'text', 'Upon the bridge, where duty bids us stand,\nA tabby of the warmest tangerine,\nWith feline grace defies the captain''s hand\nAnd treads the helm with footfall light, serene.\n\nNo Klingon foe nor anomaly arrayed\nCan match the menace of his sudden leap;\nThe console glows where Spot in mirth has played,\nAnd alarms ring out where he chose to sleep.\n\nYet Data, faithful keeper, smiles unseen —\nAn android''s joy, though circuited and spare —\nFor in this beast a mystery serene\nReflects the very life he hopes to share.\n\nSo bless thee, Spot, of fur and quiet purr:\nThou art my muse, my console saboteur.', 'finished_successfully', 0, 1.0, 'gpt-5', '2370-10-24T08:02:00.000000+00:00', NULL, '{"author":{"metadata":{},"name":null,"role":"assistant"},"channel":null,"create_time":12648384120,"end_turn":false,"id":"msg-fake-spot-0002","metadata":{"model_slug":"gpt-5"},"recipient":"all","status":"finished_successfully","update_time":null,"weight":1}', 'api', '2369-04-15T00:00:00+00:00');
INSERT INTO `openai_messages` (`conversation_id`, `message_id`, `parent_id`, `role`, `recipient`, `channel`, `content_type`, `text`, `status`, `end_turn`, `weight`, `model_slug`, `create_time`, `update_time`, `raw_json`, `source`, `last_seen_at`) VALUES ('68fa0001-fake-7000-8000-positronic0001', 'msg-fake-spot-0003', 'msg-fake-spot-0002', 'user', 'all', NULL, 'text', 'Curious. The closing couplet is satisfying. Thank you.', 'finished_successfully', 1, 1.0, NULL, '2370-10-24T08:05:00.000000+00:00', NULL, '{"author":{"metadata":{},"name":null,"role":"user"},"channel":null,"create_time":12648384300,"end_turn":true,"id":"msg-fake-spot-0003","metadata":{},"recipient":"all","status":"finished_successfully","update_time":null,"weight":1}', 'api', '2369-04-15T00:00:00+00:00');
