load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

exports_files(["Cargo.toml"])

rust_library(
    name = "datalib_etl_chat_common",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "datalib_etl_chat_common",
    edition = "2021",
    visibility = ["//datalib:__subpackages__"],
    deps = [
        "//datalib/backend/etl:datalib_etl",
        "//datalib/backend/index_lib:datalib_index_lib",
        "//datalib/backend/schema:datalib_schema",
        "//datalib/backend/time:datalib_time",
        "@datalib_crates//:anyhow",
        "@datalib_crates//:serde",
        "@datalib_crates//:serde_json",
        "@datalib_crates//:sha2",
        "@datalib_crates//:tracing",
        "@datalib_crates//:uuid",
    ],
)

rust_test(
    name = "chat_common_unittests",
    size = "small",
    crate = ":datalib_etl_chat_common",
    edition = "2021",
)
