[package]
name = "datalib-etl-timeseries-render"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[lib]
name = "datalib_etl_timeseries_render"
path = "src/lib.rs"

[dependencies]
datalib-time = { path = "../../time" }
anyhow = { workspace = true }
serde_json = { workspace = true }
