//! Shared HTTP transport for every provider's Extract step.
//!
//! Every provider's downloader ultimately shells out to `latchkey curl`
//! (so auth headers and TLS impersonation are handled uniformly). This
//! module exposes a single [`latchkey_curl`] entry point that:
//!
//! - In **Live** mode (default), runs the subprocess and parses the
//!   full HTTP response — status line, every response header, and body
//!   bytes. This is a strict superset of what individual providers used
//!   to capture; in particular anthropic and notion used to only fetch
//!   the status code via `-w "%{http_code}"` and threw the response
//!   headers away. They now get them for free.
//!
//! - In **Playback** mode (when `FRANKWEILER_HTTP_PLAYBACK=<dir>` is
//!   set), looks up a pre-recorded synthetic fixture under
//!   `<dir>/<provider>/<key>.json` and returns it without touching the
//!   network. Fixtures are hand-constructed or generated by per-provider
//!   synthesizers; we never record live traffic into the repo.
//!
//! The same `HttpResponse` shape flows out of both modes, so callers
//! cannot tell the difference and tests double as playback exercisers.
//!
//! ## Rate limits and retries
//!
//! [`latchkey_curl`] is also the single place rate-limit handling lives.
//! On an HTTP 429 it waits the `Retry-After` the server asked for (else
//! backs off exponentially); transient transport failures and 5xx are
//! retried the same way. How long it keeps trying before giving up is
//! governed by the per-source [`crate::retry::RetryGuard`] the orchestrator
//! installs (resolved from each source's `extract_params`), so the give-up
//! policy is enforced once, centrally, rather than re-implemented in every
//! provider. Providers whose rate-limit signal isn't visible by status code
//! (Slack's HTTP-200 `ratelimited` body, GitHub's primary-limit 403) feed
//! the same loop via a custom classifier — see [`latchkey_curl_classified`].

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::process::Stdio;
use std::time::Duration;

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use tokio::io::AsyncWriteExt;

use crate::latchkey::latchkey_tokio_command;

/// HTTP method. We only model the methods any provider currently issues;
/// extend as needed.
///
/// `Propfind` / `Report` are WebDAV verbs (RFCs 4918 + 6578) used by
/// the CardDAV provider for collection discovery and sync-collection
/// REPORTs. curl forwards them via `-X <METHOD>` like POST does.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum HttpMethod {
    Get,
    Post,
    Propfind,
    Report,
}

impl HttpMethod {
    fn as_str(self) -> &'static str {
        match self {
            HttpMethod::Get => "GET",
            HttpMethod::Post => "POST",
            HttpMethod::Propfind => "PROPFIND",
            HttpMethod::Report => "REPORT",
        }
    }

    /// True for methods that get a `-X <METHOD>` flag — i.e. anything
    /// other than the default `GET`. Keeps the curl invocation in
    /// [`live::send`] from having to enumerate the verbs by name.
    fn needs_x_flag(self) -> bool {
        !matches!(self, HttpMethod::Get)
    }
}

/// A single outbound HTTP request. `provider` is a short tag used to
/// namespace playback fixtures (`"slack"`, `"github"`, etc.) and tag
/// telemetry events; do **not** include the Authorization header — that
/// is injected by `latchkey` based on the URL host.
#[derive(Debug, Clone)]
pub struct HttpRequest {
    pub provider: &'static str,
    pub method: HttpMethod,
    pub url: String,
    pub headers: BTreeMap<String, String>,
    pub body: Option<Vec<u8>>,
    pub timeout: Duration,
    /// Skip the `latchkey` credential-injecting shim and shell out to
    /// plain `curl`. For *publicly* reachable resources that need no auth
    /// (e.g. a LinkedIn profile's public `og:image`) — they'd have no
    /// latchkey service registered and would otherwise fail the host
    /// allowlist. The retry/backoff loop and playback still apply; this
    /// flag is behavior-only and is NOT part of [`fixture_key`], so a
    /// synthesizer's fixtures match whether or not the bypass is set.
    pub bypass_latchkey: bool,
}

impl HttpRequest {
    pub fn get(provider: &'static str, url: impl Into<String>) -> Self {
        Self {
            provider,
            method: HttpMethod::Get,
            url: url.into(),
            headers: BTreeMap::new(),
            body: None,
            timeout: Duration::from_secs(60),
            bypass_latchkey: false,
        }
    }

    pub fn post_json(provider: &'static str, url: impl Into<String>, body: Vec<u8>) -> Self {
        let mut headers = BTreeMap::new();
        headers.insert("Content-Type".into(), "application/json".into());
        Self {
            provider,
            method: HttpMethod::Post,
            url: url.into(),
            headers,
            body: Some(body),
            timeout: Duration::from_secs(60),
            bypass_latchkey: false,
        }
    }

    pub fn header(mut self, name: impl Into<String>, value: impl Into<String>) -> Self {
        self.headers.insert(name.into(), value.into());
        self
    }

    pub fn timeout(mut self, timeout: Duration) -> Self {
        self.timeout = timeout;
        self
    }

    /// Send via plain `curl`, bypassing the latchkey shim — for public,
    /// auth-free resources. See [`HttpRequest::bypass_latchkey`].
    pub fn plain(mut self) -> Self {
        self.bypass_latchkey = true;
        self
    }
}

/// A fully-captured HTTP response. Header names are normalized to
/// lower-case so callers can probe `response.header("link")` regardless
/// of how the upstream server cased them.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HttpResponse {
    pub status: u16,
    pub headers: BTreeMap<String, String>,
    /// Body bytes. Use [`HttpResponse::body_str`] for textual responses.
    pub body: Vec<u8>,
    /// Wall-clock duration of the underlying network exchange. Zero in
    /// playback mode.
    #[serde(default)]
    pub duration_ms: u64,
}

impl HttpResponse {
    pub fn body_str(&self) -> std::borrow::Cow<'_, str> {
        String::from_utf8_lossy(&self.body)
    }

    pub fn header(&self, name: &str) -> Option<&str> {
        self.headers
            .get(&name.to_ascii_lowercase())
            .map(|s| s.as_str())
    }
}

#[derive(thiserror::Error, Debug)]
pub enum HttpError {
    #[error("{provider}: spawn latchkey failed: {message}")]
    Spawn {
        provider: &'static str,
        message: String,
    },
    #[error("{provider}: latchkey curl timed out after {timeout_ms}ms ({url})")]
    Timeout {
        provider: &'static str,
        url: String,
        timeout_ms: u64,
    },
    /// `latchkey curl` exited non-zero. This is a transport-level failure
    /// (DNS, TLS, allowlist) — *not* a non-2xx HTTP status. For HTTP
    /// errors, inspect `HttpResponse::status` on the Ok path.
    #[error("{provider}: latchkey curl exit {exit} ({url}): {stderr}")]
    Curl {
        provider: &'static str,
        url: String,
        exit: i32,
        stderr: String,
    },
    #[error("{provider}: malformed response from latchkey curl ({url}): {message}")]
    Malformed {
        provider: &'static str,
        url: String,
        message: String,
    },
    #[error("playback miss: {0}")]
    PlaybackMiss(String),
    #[error("playback fixture invalid: {0}")]
    PlaybackInvalid(String),
    /// The shared retry loop respected rate limits / backed off but the
    /// orchestrator's give-up policy ([`crate::retry::RetryGuard`]) tripped
    /// before the request ever succeeded. Terminal — the caller should
    /// surface it as a hard error for this source.
    #[error("{provider}: gave up retrying ({url}): {reason}")]
    GaveUp {
        provider: &'static str,
        url: String,
        reason: String,
    },
}

/// Environment variable a caller (genrule, hermetic test, dev loop) can
/// set to switch every provider into fixture playback. Value is a
/// directory; per-request fixtures live at `<dir>/<provider>/<key>.json`.
pub const PLAYBACK_ENV: &str = "FRANKWEILER_HTTP_PLAYBACK";

enum Mode {
    Live,
    Playback(PathBuf),
}

impl Mode {
    fn current() -> Self {
        match std::env::var_os(PLAYBACK_ENV) {
            Some(v) if !v.is_empty() => Mode::Playback(PathBuf::from(v)),
            _ => Mode::Live,
        }
    }
}

/// A single `Retry-After` wait is capped here so one pathological header
/// (or a far-future `x-ratelimit-reset`) can't park a source for hours. The
/// give-up policy ([`crate::retry::RetryGuard`]) still bounds total effort;
/// this just keeps any *single* sleep sane. Realistic values (seconds to a
/// few minutes) are respected exactly.
const MAX_RETRY_AFTER: Duration = Duration::from_secs(600);

/// What the retry loop should do with one completed attempt's response.
/// Returned by the response classifier passed to [`latchkey_curl_classified`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Retryability {
    /// Definitive — hand the response back to the caller unchanged (any 2xx,
    /// and 4xx the caller wants to inspect like 401/404).
    Accept,
    /// Rate-limited / transient — back off and retry, honoring `retry_after`
    /// (from `Retry-After` or a provider-specific reset header) when known.
    Retry { retry_after: Option<Duration> },
}

/// Default response classifier: HTTP 429 and 502–504 are retryable
/// (honoring `Retry-After`); everything else is accepted. This is what
/// [`latchkey_curl`] uses. Providers whose rate-limit signal isn't visible
/// by status code (Slack's HTTP-200 `error:"ratelimited"` body, GitHub's
/// `403 + x-ratelimit-remaining:0`) wrap this with their own classifier and
/// call [`latchkey_curl_classified`].
pub fn default_retryability(resp: &HttpResponse) -> Retryability {
    match resp.status {
        429 | 502 | 503 | 504 => Retryability::Retry {
            retry_after: parse_retry_after(resp.header("retry-after")),
        },
        _ => Retryability::Accept,
    }
}

/// Parse a `Retry-After` header value into a wait duration. Supports the
/// delta-seconds form (`"120"`) and the HTTP-date form
/// (`"Wed, 21 Oct 2015 07:28:00 GMT"`). Capped at [`MAX_RETRY_AFTER`].
/// Returns `None` when absent or unparseable (the loop then backs off).
pub fn parse_retry_after(value: Option<&str>) -> Option<Duration> {
    let v = value?.trim();
    if let Ok(secs) = v.parse::<u64>() {
        return Some(Duration::from_secs(secs).min(MAX_RETRY_AFTER));
    }
    if let Ok(when) = chrono::DateTime::parse_from_rfc2822(v) {
        let delta = when.with_timezone(&chrono::Utc) - chrono::Utc::now();
        let secs = delta.num_seconds().max(0) as u64;
        return Some(Duration::from_secs(secs).min(MAX_RETRY_AFTER));
    }
    None
}

/// Issue an HTTP request and return the full response, with the shared
/// retry policy applied (429 + 5xx + transient-transport, honoring
/// `Retry-After` else exponential backoff, bounded by the ambient
/// [`crate::retry::RetryGuard`]). Dispatches between the live
/// (`latchkey curl`) and playback (disk-fixture) implementations based on
/// `FRANKWEILER_HTTP_PLAYBACK`. This is the entry point for every provider
/// whose rate-limit signal is expressible by status code.
pub async fn latchkey_curl(req: &HttpRequest) -> Result<HttpResponse, HttpError> {
    latchkey_curl_classified(req, default_retryability).await
}

/// Like [`latchkey_curl`], but the caller supplies a response classifier so
/// a provider can mark responses the status code alone can't (e.g. Slack's
/// HTTP-200 `ratelimited` body) as retryable. Transport-level transients
/// (curl exit 7/28/35/56, timeouts) are always retried regardless of the
/// classifier, since there is no response to classify.
pub async fn latchkey_curl_classified<F>(
    req: &HttpRequest,
    classify: F,
) -> Result<HttpResponse, HttpError>
where
    F: Fn(&HttpResponse) -> Retryability,
{
    // Resolve the current source's give-up guard (or a default-bounded
    // throwaway outside any extract scope). It owns both the give-up limits
    // and the backoff schedule.
    let guard = crate::retry::current_or_default();
    let mut backoff = guard.initial_backoff();
    loop {
        // Count every outbound *attempt* against the current source's
        // extract metrics (no-op outside an extract scope). This is the
        // single transport chokepoint every provider's API call funnels
        // through, so the per-source API-call total is captured here with
        // zero provider-side code. File-based ingestion never reaches this
        // path, so it correctly reports zero requests.
        crate::extract_metrics::record_api_request();
        let outcome = match Mode::current() {
            Mode::Live => live::send(req).await,
            Mode::Playback(root) => playback::lookup(req, &root).await,
        };

        // Decide whether this attempt is retryable. `None` = accept (success
        // or a definitive response/error → hand back to the caller as-is);
        // `Some(retry_after)` = retryable failure.
        let retry: Option<Option<Duration>> = match &outcome {
            Ok(resp) => match classify(resp) {
                Retryability::Accept => None,
                Retryability::Retry { retry_after } => Some(retry_after),
            },
            // Transient transport failures: retry without a server-specified
            // delay. (7 couldn't connect, 28 timeout, 35 TLS, 56 recv error.)
            Err(HttpError::Timeout { .. }) => Some(None),
            Err(HttpError::Curl { exit, .. }) if matches!(*exit, 7 | 28 | 35 | 56) => Some(None),
            // Spawn / Malformed / Playback* / GaveUp: terminal, return as-is.
            Err(_) => None,
        };

        let Some(retry_after) = retry else {
            // Accepted — record forward progress and hand the response (or
            // terminal error) back to the caller untouched.
            guard.on_progress();
            return outcome;
        };

        // Retryable failure: consult the give-up guard before sleeping.
        if let crate::retry::GuardVerdict::GiveUp(reason) = guard.on_failure() {
            let detail = match &outcome {
                Ok(resp) => format!("HTTP {}", resp.status),
                Err(e) => e.to_string(),
            };
            return Err(HttpError::GaveUp {
                provider: req.provider,
                url: req.url.clone(),
                reason: format!("{reason}; last attempt: {detail}"),
            });
        }

        let wait = retry_after
            .map(|d| d.min(MAX_RETRY_AFTER))
            .unwrap_or(backoff);
        tracing::warn!(
            provider = req.provider,
            url = %req.url,
            wait_ms = wait.as_millis() as u64,
            "rate-limited / transient; backing off then retrying",
        );
        tokio::time::sleep(wait).await;
        backoff = std::cmp::min(backoff * 2, guard.max_backoff());
    }
}

// ---------------------------------------------------------------------------
// Live mode: shell out to `latchkey curl`.
// ---------------------------------------------------------------------------

mod live {
    use super::*;

    pub(super) async fn send(req: &HttpRequest) -> Result<HttpResponse, HttpError> {
        let body_file = tempfile::NamedTempFile::new().map_err(|e| HttpError::Spawn {
            provider: req.provider,
            message: format!("tempfile: {e}"),
        })?;
        let body_path = body_file.path().to_path_buf();

        // `latchkey curl …` for the credential-injecting shim, or plain
        // `curl …` when the caller opted out (public, auth-free fetch).
        let mut cmd = if req.bypass_latchkey {
            tokio::process::Command::new("curl")
        } else {
            let mut c = latchkey_tokio_command();
            c.arg("curl");
            c
        };
        cmd.arg("-sS");
        // -D - dumps the response header block to stdout so we can
        // parse every header. -o <path> writes the body to a tempfile
        // so headers and body are cleanly separated (no need to split
        // on a CRLFCRLF boundary).
        cmd.args(["-D", "-", "-o"]).arg(&body_path);
        if req.method.needs_x_flag() {
            cmd.args(["-X", req.method.as_str()]);
        }
        for (k, v) in &req.headers {
            cmd.arg("-H").arg(format!("{}: {}", k, v));
        }
        let writes_body_to_stdin = req.body.is_some();
        if writes_body_to_stdin {
            // `@-` reads the request body from stdin so we don't smuggle
            // it through argv (avoids ARG_MAX and lets binary payloads
            // round-trip cleanly).
            cmd.arg("--data-binary").arg("@-");
            cmd.stdin(Stdio::piped());
        }
        cmd.arg(&req.url);
        cmd.stdout(Stdio::piped());
        cmd.stderr(Stdio::piped());

        let timeout_ms = req.timeout.as_millis() as u64;
        let t0 = std::time::Instant::now();
        let proc_result = tokio::time::timeout(req.timeout, async {
            let mut child = cmd.spawn().map_err(|e| HttpError::Spawn {
                provider: req.provider,
                message: e.to_string(),
            })?;
            if writes_body_to_stdin {
                if let (Some(mut stdin), Some(payload)) = (child.stdin.take(), req.body.as_ref()) {
                    stdin
                        .write_all(payload)
                        .await
                        .map_err(|e| HttpError::Spawn {
                            provider: req.provider,
                            message: format!("write stdin: {e}"),
                        })?;
                    stdin.shutdown().await.map_err(|e| HttpError::Spawn {
                        provider: req.provider,
                        message: format!("close stdin: {e}"),
                    })?;
                }
            }
            child
                .wait_with_output()
                .await
                .map_err(|e| HttpError::Spawn {
                    provider: req.provider,
                    message: e.to_string(),
                })
        })
        .await
        .map_err(|_| HttpError::Timeout {
            provider: req.provider,
            url: req.url.clone(),
            timeout_ms,
        })?;
        let proc = proc_result?;
        let duration_ms = t0.elapsed().as_millis() as u64;

        if !proc.status.success() {
            let stderr = String::from_utf8_lossy(&proc.stderr);
            return Err(HttpError::Curl {
                provider: req.provider,
                url: req.url.clone(),
                exit: proc.status.code().unwrap_or(-1),
                stderr: stderr.chars().take(400).collect(),
            });
        }

        let header_dump = String::from_utf8_lossy(&proc.stdout).into_owned();
        let (status, headers) =
            parse_header_block(&header_dump).ok_or_else(|| HttpError::Malformed {
                provider: req.provider,
                url: req.url.clone(),
                message: format!(
                    "no HTTP status line in header dump: {:?}",
                    header_dump.chars().take(120).collect::<String>()
                ),
            })?;
        let body = std::fs::read(&body_path).map_err(|e| HttpError::Malformed {
            provider: req.provider,
            url: req.url.clone(),
            message: format!("read body tempfile: {e}"),
        })?;

        Ok(HttpResponse {
            status,
            headers,
            body,
            duration_ms,
        })
    }

    /// Parse the `-D -` header dump. curl emits multiple header blocks
    /// when it follows redirects or sees `HTTP/1.1 100 Continue`; we
    /// keep the *last* block, which is the final response.
    fn parse_header_block(dump: &str) -> Option<(u16, BTreeMap<String, String>)> {
        let normalized = dump.replace("\r\n", "\n");
        let blocks: Vec<&str> = normalized
            .split("\n\n")
            .filter(|b| !b.trim().is_empty())
            .collect();
        let last = blocks.last()?;
        let mut lines = last.lines();
        let status_line = lines.next()?;
        let parts: Vec<&str> = status_line.split_whitespace().collect();
        if parts.len() < 2 {
            return None;
        }
        let status: u16 = parts[1].parse().ok()?;
        let mut headers = BTreeMap::new();
        for line in lines {
            if let Some((k, v)) = line.split_once(':') {
                headers.insert(k.trim().to_ascii_lowercase(), v.trim().to_string());
            }
        }
        Some((status, headers))
    }

    #[cfg(test)]
    mod tests {
        use super::*;

        #[test]
        fn parses_simple_header_block() {
            let dump = "HTTP/2 200\r\ncontent-type: application/json\r\nx-ratelimit-remaining: 4999\r\n\r\n";
            let (status, headers) = parse_header_block(dump).unwrap();
            assert_eq!(status, 200);
            assert_eq!(headers.get("content-type").unwrap(), "application/json");
            assert_eq!(headers.get("x-ratelimit-remaining").unwrap(), "4999");
        }

        #[test]
        fn keeps_last_block_after_continue() {
            let dump = "HTTP/1.1 100 Continue\r\n\r\nHTTP/1.1 200 OK\r\nlink: <next>; rel=\"next\"\r\n\r\n";
            let (status, headers) = parse_header_block(dump).unwrap();
            assert_eq!(status, 200);
            assert!(headers.get("link").unwrap().contains("rel=\"next\""));
        }
    }
}

// ---------------------------------------------------------------------------
// Playback mode: read pre-recorded fixtures from disk.
// ---------------------------------------------------------------------------

mod playback {
    use super::*;

    pub(super) async fn lookup(req: &HttpRequest, root: &Path) -> Result<HttpResponse, HttpError> {
        let key = fixture_key(req);
        let path = root.join(req.provider).join(&key);
        let bytes = tokio::fs::read(&path).await.map_err(|_| {
            HttpError::PlaybackMiss(format!(
                "{}: no fixture for {} {} (key={})",
                path.display(),
                req.method.as_str(),
                req.url,
                key
            ))
        })?;
        let resp: HttpResponse = serde_json::from_slice(&bytes)
            .map_err(|e| HttpError::PlaybackInvalid(format!("{}: {e}", path.display())))?;
        Ok(resp)
    }
}

/// Stable filename a request maps to in the playback root. Used both by
/// `latchkey_curl` (to look up fixtures) and by per-provider synthesizers
/// (to write them). Format: `<METHOD>-<sha256-prefix>.json`. The sha256
/// digest folds in the canonicalized URL, the headers (other than ones
/// latchkey injects), and the body — so two POSTs to the same endpoint
/// with different payloads land in different files.
pub fn fixture_key(req: &HttpRequest) -> String {
    let mut h = Sha256::new();
    h.update(req.method.as_str().as_bytes());
    h.update(b"\n");
    h.update(canonical_url(&req.url).as_bytes());
    h.update(b"\n");
    for (k, v) in &req.headers {
        h.update(k.to_ascii_lowercase().as_bytes());
        h.update(b": ");
        h.update(v.as_bytes());
        h.update(b"\n");
    }
    h.update(b"\n");
    if let Some(body) = &req.body {
        h.update(body);
    }
    let digest = h.finalize();
    // 32 hex chars (128 bits) — plenty to avoid collisions in any
    // realistic fixture set, short enough to read in a directory listing.
    format!("{}-{:.32x}.json", req.method.as_str(), digest)
}

/// Canonicalize a URL for fixture-key hashing: sort query parameters by
/// key. Order shouldn't change a server's response, but client code may
/// emit params in different orders across versions; canonicalizing keeps
/// fixtures stable.
fn canonical_url(url: &str) -> String {
    let Some((base, query)) = url.split_once('?') else {
        return url.to_string();
    };
    if query.is_empty() {
        return base.to_string();
    }
    let mut params: Vec<(&str, &str)> = query
        .split('&')
        .map(|p| p.split_once('=').unwrap_or((p, "")))
        .collect();
    params.sort_by(|a, b| a.0.cmp(b.0).then(a.1.cmp(b.1)));
    let rebuilt = params
        .iter()
        .map(|(k, v)| format!("{k}={v}"))
        .collect::<Vec<_>>()
        .join("&");
    format!("{base}?{rebuilt}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fixture_key_is_stable_under_query_param_order() {
        let a = HttpRequest::get(
            "slack",
            "https://slack.com/api/conversations.history?channel=C1&limit=100",
        );
        let b = HttpRequest::get(
            "slack",
            "https://slack.com/api/conversations.history?limit=100&channel=C1",
        );
        assert_eq!(fixture_key(&a), fixture_key(&b));
    }

    #[test]
    fn fixture_key_distinguishes_methods() {
        let g = HttpRequest::get("notion", "https://api.notion.com/v1/search");
        let p =
            HttpRequest::post_json("notion", "https://api.notion.com/v1/search", b"{}".to_vec());
        assert_ne!(fixture_key(&g), fixture_key(&p));
    }

    #[test]
    fn fixture_key_distinguishes_post_bodies() {
        let a = HttpRequest::post_json(
            "notion",
            "https://api.notion.com/v1/search",
            b"{\"q\":\"a\"}".to_vec(),
        );
        let b = HttpRequest::post_json(
            "notion",
            "https://api.notion.com/v1/search",
            b"{\"q\":\"b\"}".to_vec(),
        );
        assert_ne!(fixture_key(&a), fixture_key(&b));
    }

    #[tokio::test]
    async fn playback_miss_returns_named_error() {
        let dir = tempfile::tempdir().unwrap();
        std::env::set_var(PLAYBACK_ENV, dir.path());
        let req = HttpRequest::get("slack", "https://slack.com/api/auth.test");
        let err = latchkey_curl(&req).await.unwrap_err();
        std::env::remove_var(PLAYBACK_ENV);
        match err {
            HttpError::PlaybackMiss(msg) => assert!(msg.contains("auth.test"), "{msg}"),
            other => panic!("expected PlaybackMiss, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn playback_round_trips_a_synthetic_fixture() {
        let dir = tempfile::tempdir().unwrap();
        let req = HttpRequest::get("slack", "https://slack.com/api/auth.test");
        let key = fixture_key(&req);
        let provider_dir = dir.path().join("slack");
        std::fs::create_dir_all(&provider_dir).unwrap();
        let response = HttpResponse {
            status: 200,
            headers: {
                let mut h = BTreeMap::new();
                h.insert("content-type".into(), "application/json".into());
                h
            },
            body: br#"{"ok":true,"team":"Test"}"#.to_vec(),
            duration_ms: 0,
        };
        std::fs::write(
            provider_dir.join(&key),
            serde_json::to_vec(&response).unwrap(),
        )
        .unwrap();
        std::env::set_var(PLAYBACK_ENV, dir.path());
        let got = latchkey_curl(&req).await.unwrap();
        std::env::remove_var(PLAYBACK_ENV);
        assert_eq!(got.status, 200);
        assert_eq!(got.header("content-type"), Some("application/json"));
        assert_eq!(got.body_str(), r#"{"ok":true,"team":"Test"}"#);
    }

    #[test]
    fn parse_retry_after_handles_seconds_and_garbage() {
        assert_eq!(parse_retry_after(Some("7")), Some(Duration::from_secs(7)));
        assert_eq!(
            parse_retry_after(Some("  12 ")),
            Some(Duration::from_secs(12))
        );
        // Capped at MAX_RETRY_AFTER.
        assert_eq!(parse_retry_after(Some("100000")), Some(MAX_RETRY_AFTER));
        assert_eq!(parse_retry_after(None), None);
        assert_eq!(parse_retry_after(Some("soon")), None);
    }

    #[test]
    fn default_retryability_classifies_status() {
        let mk = |status: u16, ra: Option<&str>| {
            let mut headers = BTreeMap::new();
            if let Some(v) = ra {
                headers.insert("retry-after".to_string(), v.to_string());
            }
            HttpResponse {
                status,
                headers,
                body: Vec::new(),
                duration_ms: 0,
            }
        };
        assert_eq!(default_retryability(&mk(200, None)), Retryability::Accept);
        assert_eq!(default_retryability(&mk(404, None)), Retryability::Accept);
        assert_eq!(
            default_retryability(&mk(429, Some("5"))),
            Retryability::Retry {
                retry_after: Some(Duration::from_secs(5))
            }
        );
        assert_eq!(
            default_retryability(&mk(503, None)),
            Retryability::Retry { retry_after: None }
        );
    }

    /// A playback fixture that always returns 429 should be retried until
    /// the ambient guard's sequential-failure limit trips, then surface as
    /// `GaveUp`. Uses near-zero backoff so the test is fast.
    #[tokio::test]
    async fn retries_429_then_gives_up_per_guard() {
        let dir = tempfile::tempdir().unwrap();
        let req = HttpRequest::get("slack", "https://slack.com/api/auth.test");
        let key = fixture_key(&req);
        let provider_dir = dir.path().join("slack");
        std::fs::create_dir_all(&provider_dir).unwrap();
        let response = HttpResponse {
            status: 429,
            headers: BTreeMap::new(),
            body: b"slow down".to_vec(),
            duration_ms: 0,
        };
        std::fs::write(
            provider_dir.join(&key),
            serde_json::to_vec(&response).unwrap(),
        )
        .unwrap();

        std::env::set_var(PLAYBACK_ENV, dir.path());
        let fast = Duration::from_millis(1);
        let guard = crate::retry::RetryGuard::new(Duration::from_secs(3600), 3, fast, fast);
        let err = crate::retry::scope(guard, async { latchkey_curl(&req).await })
            .await
            .unwrap_err();
        std::env::remove_var(PLAYBACK_ENV);
        match err {
            HttpError::GaveUp { reason, .. } => {
                assert!(reason.contains("sequential failed requests"), "{reason}");
                assert!(reason.contains("HTTP 429"), "{reason}");
            }
            other => panic!("expected GaveUp, got {other:?}"),
        }
    }
}
