#!/bin/sh
# Stage the `datalib-step-*` wrapper scripts next to an already-staged
# `datalib-step` binary: `stage_wrappers.sh <dir>`.
#
# The wrappers are a *virtual split* of the datalib-step monolith: one
# tiny `#!/bin/sh` script per built-in step (`datalib-step-download-
# slack_api`, `datalib-step-render-perseus`, `datalib-step-grid_index`,
# …), each exec'ing the sibling monolith with the subcommand words
# baked in. Configs name the wrapper (`command:
# datalib-step-download-slack_api`) so each step reads as its own
# binary, while the bytes on disk stay one shared binary — an actual
# split would duplicate the ~40 MB of shared runtime per step (tokio,
# sqlx, the etl framework) for ~1.6 MB of per-provider code.
#
# Callers (keep in sync when adding a staging path):
#   * frankweiler/{serve_dev,dev,dev_perseus}.sh — dev bindir staging
#   * .github/workflows/release.yml — release tarball stage step
#   * frankweiler/tauri/build.rs — stages binaries/ for the .app bundle
#   * tests/fixtures/run_sync_pipeline.py — fixture-pipeline bindir
#     (path plumbed in via $STAGE_WRAPPERS_SH)
#
# The old spelled-out form (`command: datalib-step download slack_api`)
# still works — the monolith keeps its subcommands — so existing user
# configs need no migration.
set -eu

dir="${1:?usage: stage_wrappers.sh <dir holding datalib-step>}"
[ -d "$dir" ] || { echo "stage_wrappers.sh: not a directory: $dir" >&2; exit 1; }

# One entry per source type — keep in sync with SOURCE_TYPES in
# src/dispatch.rs; step_wrappers_consistency_test enforces the match.
source_types="
beeper
carddav
chatgpt_api
claude_api
claude_export
email
fsindex
github_api
gitlab_api
google_takeout
linkedin
notion_api
perseus
signal_backup
slack_api
sms_backup_restore
whatsapp_backup
yolink
"

# write_wrapper <name> <subcommand words…>
write_wrapper() {
    name="$1"
    shift
    cat > "$dir/$name" <<EOF
#!/bin/sh
# Generated by stage_wrappers.sh — thin alias over the datalib-step
# monolith (virtual split; see that script for why).
exec "\$(dirname "\$0")/datalib-step" $* "\$@"
EOF
    chmod 755 "$dir/$name"
}

for ty in $source_types; do
    write_wrapper "datalib-step-download-$ty" download "$ty"
    write_wrapper "datalib-step-render-$ty" render "$ty"
done
write_wrapper datalib-step-grid_index grid_index
write_wrapper datalib-step-qmd_index qmd_index
