"""AUTOGENERATED by schemas/codegen.py — do not edit. Source: grid_rows.schema.json."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class GridRow:
    """One row in the grid_rows table. Producers (provider ingesters in src/ingest/providers/<p>/ingest.py) emit one or more GridRow per source entity; consumers (frankweiler/backend/core/src/db.rs and frankweiler/ui/src/SearchView.vue) read them as a single union."""

    uuid: str
    """Stable, globally-unique row identifier. Must be deterministic from the source entity so re-ingest is idempotent.

    Per-provider mapping:
      anthropic.chat: anthropic_conversations.conversation_uuid
      anthropic.message: anthropic_messages.message_uuid
      anthropic.block: format!('{}:{}', message_uuid, block_index)
      openai.chat: openai_conversations.conversation_id
      openai.message: openai_messages.message_id
      slack.thread: uuidv5(SLACK_NS, 'slack:{team}:{channel}:{thread_ts}')
      slack.message: uuidv5(SLACK_NS, 'slack:{team}:{channel}:{ts}')
    """
    provider: str
    """Which provider this row originated from. Determines which per-provider table to consult for the raw payload."""
    kind: str
    """Row category as displayed in the Kind column. Drives the row-type filter (chat: vs message:) and the icon.

    Per-provider mapping:
      anthropic.chat: 'Chat'
      anthropic.message.human: 'User Input'
      anthropic.message.assistant: 'LLM Response'
      anthropic.block.thinking: 'LLM Thinking'
      anthropic.block.tool_*: 'Tool Call'
      openai.chat: 'Chat'
      openai.message.user: 'User Input'
      openai.message.assistant.thoughts|reasoning_recap: 'LLM Thinking'
      openai.message.assistant.*: 'LLM Response'
      openai.message.system|*: 'Tool Call'
      slack.thread: 'Slack Thread'
      slack.message: 'Slack Message'
    """
    source_label: str
    """Human-friendly provider label shown in the Source column.

    Per-provider mapping:
      anthropic: 'Claude'
      openai: 'ChatGPT'
      slack: 'Slack'
    """
    when_ts: str
    """ISO-8601 timestamp with explicit offset, used for global sort and before:/after: filters. Synthesized for blocks/messages without their own timestamp by bumping microseconds off the parent's timestamp so within-conversation order stays stable.

    Per-provider mapping:
      anthropic.chat: IFNULL(created_at, updated_at)
      anthropic.message: messages.created_at
      anthropic.block: blocks.start_timestamp OR bump_micros(parent_msg.created_at, block_index+1)
      openai.chat: IFNULL(create_time, update_time)
      openai.message: messages.create_time OR bump_micros(parent_conv.create_time, msg_idx+1)
      slack.message: slack_messages.ts (Slack ts is unix-seconds-with-fractional, formatted as ISO-8601 in UTC)
    """
    author: str | None
    """Display name of the message author. For LLM responses this is typically the model slug; for user inputs, the account; for Slack, the user real_name.

    Per-provider mapping:
      anthropic.chat: ''
      anthropic.message.human: account_uuid
      anthropic.message.assistant: conversation.raw_json.model OR sender
      openai.message.user: account_id
      openai.message.assistant: model_slug OR role
      slack.message: users.real_name OR users.name
    """
    account: str | None
    """Account identifier (provider-native). Drives the account: filter.

    Per-provider mapping:
      anthropic: anthropic_conversations.account_uuid
      openai: openai_conversations.account_id
      slack: slack_workspaces.team_id
    """
    project: str | None
    """Project identifier. Currently only Anthropic has projects; null for everyone else.

    Per-provider mapping:
      anthropic: anthropic_conversations.project_uuid
      openai: null
      slack: null
    """
    channel: str | None
    """Slack channel display name (e.g. 'bridge', 'engineering'). Null for non-Slack rows. Drives the Channel column and a future channel: filter.

    Per-provider mapping:
      anthropic: null
      openai: null
      slack: slack_channels.channel_name
    """
    conversation_name: str | None
    """Human-readable parent conversation title — drives the Conversation Name grid column. For Chat rows this duplicates the row's own title; for messages/blocks it carries the parent thread's title so each grid row stands alone without a join.

    Per-provider mapping:
      anthropic: anthropic_conversations.name
      openai: openai_conversations.title
      slack: slack_channels.channel_name + thread root snippet
    """
    conversation_uuid: str
    """Parent conversation / thread UUID. For Chat / Slack Thread rows this equals `uuid`. For Message / block rows it points at the parent so the chat preview pane knows which thread to open.

    Per-provider mapping:
      anthropic.chat: = uuid (conversation_uuid)
      anthropic.message: messages.conversation_uuid
      anthropic.block: parent_message.conversation_uuid
      openai.chat: = uuid (conversation_id)
      openai.message: messages.conversation_id
      slack.thread: = uuid (thread root uuid)
      slack.message: thread root uuid
    """
    message_index: int | None
    """Zero-based index of this message within its conversation, in the same order the QMD file renders messages. Used by ChatPreviewPane to scroll to and highlight the clicked message via `#m-idx-{index}`. Null for Chat / Slack Thread rows."""
    entire_chat: str
    """Path used by the row to open the full thread in the right-hand preview. Today: `/chat/{conversation_uuid}`."""
    text: str
    """Full searchable body for this row. The Rust backend computes the displayed snippet from `text` + the user's free-text needle at query time, so we store the full body here rather than a pre-truncated snippet.

    Per-provider mapping:
      anthropic.chat: summary OR name
      anthropic.message: messages.text
      anthropic.block: blocks.text OR raw_json.thinking OR type
      openai.chat: title
      openai.message: messages.text
      slack.thread: root message text
      slack.message: messages.text (with mention/emoji rendering)
    """
    slack_link: str | None
    """Deep link of the form `slack://channel?team={team_id}&id={channel_id}&message={ts}` (or the https equivalent). Populated only for Slack rows; drives the 'Open in Slack' right-click context menu item."""
    qmd_path: str | None
    """Path to the rendered QMD file for this row's conversation/thread, relative to the data root. Set on every row (chat-level rows point at their own QMD; message/block rows inherit their parent thread's). The chat preview pane uses this to load the conversation directly — no glob, no frontmatter scan.

    Per-provider mapping:
      anthropic: anthropic/{account_uuid}/llm_chats/{conversation_uuid}__{slug(name)}.qmd
      openai: openai/{account_id|unknown}/llm_chats/{conversation_id}__{slug(title)}.qmd
      slack: slack/{team_id}/{channel_name}/threads/{thread_uuid}__{slug(root_text[:80])}.qmd
    """


TABLES: dict[str, str] = {
    "grid_rows": "GridRow",
}


# Portable CREATE TABLE statements for every table this schema defines.
# Same SQL subset accepted by Dolt, MySQL, and SQLite.
DDL: list[str] = [
    """
CREATE TABLE IF NOT EXISTS grid_rows (
    uuid VARCHAR(96) NOT NULL,
    provider VARCHAR(32) NOT NULL,
    kind VARCHAR(32) NOT NULL,
    source_label VARCHAR(32) NOT NULL,
    when_ts VARCHAR(40) NOT NULL,
    author VARCHAR(255),
    account VARCHAR(96),
    project VARCHAR(96),
    channel VARCHAR(255),
    conversation_name VARCHAR(512),
    conversation_uuid VARCHAR(96) NOT NULL,
    message_index INT,
    entire_chat VARCHAR(255) NOT NULL,
    text LONGTEXT NOT NULL,
    slack_link VARCHAR(512),
    qmd_path VARCHAR(512),
    PRIMARY KEY (uuid)
)
    """,
]


# Column names per table, in declaration order.
COLUMNS: dict[str, list[str]] = {
    "grid_rows": [
        "uuid",
        "provider",
        "kind",
        "source_label",
        "when_ts",
        "author",
        "account",
        "project",
        "channel",
        "conversation_name",
        "conversation_uuid",
        "message_index",
        "entire_chat",
        "text",
        "slack_link",
        "qmd_path",
    ],
}
