"""AUTOGENERATED by schemas/codegen.py — do not edit. Source: sync_jobs.schema.json."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class SyncJobRow:
    """One row in the `sync_jobs` table. UI polls `GET /api/sync/jobs/{id}` to render the Lightroom-style progress chrome; cancel flips `state` to `canceled` and the worker SIGTERMs its child."""

    id: str
    """Client-or-backend-generated UUIDv4. Used as the row primary key and in `dolt log` commit messages."""
    source_name: str | None
    """`sources[].name` from `config.yaml` this job operates on. NULL for `kind = all` parent jobs and for `kind = ingest` passes that consume every pending download_runs row across sources."""
    kind: str
    """What the job does. `download` fetches from a single source's provider; `ingest` translates queued raw files into Dolt rows; `render` re-emits markdown for documents whose cache key changed; `all` is a parent job that enqueues + waits on per-source child jobs."""
    parent_job_id: str | None
    """When this row was enqueued as a child of an `all`-kind job, points at the parent. NULL for standalone jobs. Lets the UI group `Sync all` runs into one collapsible card."""
    state: str
    """Lifecycle state. `pending` → `running` when the worker picks it up; `running` → `done` / `failed` at completion; `pending` / `running` → `canceled` when the UI requests a cancel (worker SIGTERMs the child and moves on)."""
    created_at: str
    """When the backend enqueued the row (ISO-8601 with explicit local offset, per AGENTS.md)."""
    started_at: str | None
    """When the worker flipped `state` to `running` (ISO-8601 with explicit offset). NULL while still `pending`."""
    finished_at: str | None
    """When the worker flipped `state` to a terminal value — `done`, `failed`, or `canceled` (ISO-8601 with explicit offset). NULL while still pending/running."""
    error: str | None
    """Human-readable error message when `state = failed`. The full structured log lives in `<root>/state/job-logs/<id>.log`; this column is just the summary the UI shows in the chrome."""
    pid: int | None
    """OS pid of the active child process while `state = running`. On worker startup, any `running` rows whose pid is no longer alive get flipped to `failed` (state recovery — see plan Phase D, task 16)."""
    progress_pct: float | None
    """Latest reported progress, 0.0..1.0. May be NULL when the underlying step can't report a meaningful fraction (e.g. open-ended Slack history pull). Drives the progress bar in the UI chrome."""
    progress_msg: str | None
    """Latest human-readable progress line (e.g. `downloaded 14/200 conversations`). Shown on hover over the chrome's progress bar so the user can see what the worker is actually doing — useful for distinguishing 'slow but working' from 'stuck'."""


TABLES: dict[str, str] = {
    "sync_jobs": "SyncJobRow",
}


# Portable CREATE TABLE statements for every table this schema defines.
# Same SQL subset accepted by Dolt, MySQL, and SQLite.
DDL: list[str] = [
    """
CREATE TABLE IF NOT EXISTS sync_jobs (
    id VARCHAR(36) NOT NULL,
    source_name VARCHAR(64),
    kind VARCHAR(16) NOT NULL,
    parent_job_id VARCHAR(36),
    state VARCHAR(16) NOT NULL,
    created_at VARCHAR(40) NOT NULL,
    started_at VARCHAR(40),
    finished_at VARCHAR(40),
    error TEXT,
    pid INT,
    progress_pct DOUBLE,
    progress_msg VARCHAR(512),
    PRIMARY KEY (id)
)
    """,
]


# Column names per table, in declaration order.
COLUMNS: dict[str, list[str]] = {
    "sync_jobs": [
        "id",
        "source_name",
        "kind",
        "parent_job_id",
        "state",
        "created_at",
        "started_at",
        "finished_at",
        "error",
        "pid",
        "progress_pct",
        "progress_msg",
    ],
}


# Per-column max byte length for VARCHAR(N) columns. Writers should
# truncate over-long values before INSERT — Dolt/MySQL reject the
# whole batch otherwise. Columns with TEXT/LONGTEXT types are absent
# from this map (effectively unbounded for our purposes).
MAX_LENGTHS: dict[str, dict[str, int]] = {
    "sync_jobs": {
        "id": 36,
        "source_name": 64,
        "kind": 16,
        "parent_job_id": 36,
        "state": 16,
        "created_at": 40,
        "started_at": 40,
        "finished_at": 40,
        "progress_msg": 512,
    },
}
