"""AUTOGENERATED by schemas/codegen.py — do not edit."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class Account:
    account_uuid: str
    full_name: str | None
    email_address: str | None
    first_seen_at: str
    last_seen_at: str


@dataclass
class Project:
    project_uuid: str
    account_uuid: str | None
    name: str | None
    description: str | None
    first_seen_at: str
    last_seen_at: str


@dataclass
class Conversation:
    conversation_uuid: str
    account_uuid: str
    project_uuid: str | None
    name: str | None
    summary: str | None
    created_at: str
    updated_at: str
    first_seen_at: str
    last_seen_at: str


@dataclass
class Message:
    message_uuid: str
    conversation_uuid: str
    parent_message_uuid: str | None
    sender: str
    text: str | None
    created_at: str
    updated_at: str
    first_seen_at: str
    last_seen_at: str


@dataclass
class ContentBlock:
    message_uuid: str
    ordinal: int
    type: str
    text: str | None
    metadata_json: str | None


@dataclass
class Attachment:
    attachment_uuid: str
    message_uuid: str
    file_name: str | None
    file_type: str | None
    file_size: int | None
    extracted_content: str | None


TABLES: dict[str, str] = {
    "anthropic_accounts": "Account",
    "anthropic_projects": "Project",
    "anthropic_conversations": "Conversation",
    "anthropic_messages": "Message",
    "anthropic_content_blocks": "ContentBlock",
    "anthropic_attachments": "Attachment",
}
