"""AUTOGENERATED by schemas/codegen.py — do not edit. Source: grid_rows.schema.json."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class GridRow:
    """One row in the grid_rows table. Producers (provider ingesters in src/ingest/providers/<p>/ingest.py) emit one or more GridRow per source entity; consumers (frankweiler/backend/core/src/db.rs and frankweiler/ui/src/SearchView.vue) read them as a single union."""

    uuid: str
    """Stable, globally-unique row identifier. Must be deterministic from the source entity so re-ingest is idempotent.

    Per-provider mapping:
      anthropic.chat: anthropic_conversations.conversation_uuid
      anthropic.message: anthropic_messages.message_uuid
      anthropic.block: format!('{}:{}', message_uuid, block_index)
      openai.chat: openai_conversations.conversation_id
      openai.message: openai_messages.message_id
      slack.thread: uuidv5(SLACK_NS, 'slack:{team}:{channel}:{thread_ts}')
      slack.message: uuidv5(SLACK_NS, 'slack:{team}:{channel}:{ts}')
      github.pr: uuidv5(GITHUB_NS, 'github:{repo}:pr:{number}')
      github.issue_comment: uuidv5(GITHUB_NS, 'github:{repo}:issue_comment:{id}')
      github.pr_review: uuidv5(GITHUB_NS, 'github:{repo}:pr_review:{id}')
      github.pr_review_comment: uuidv5(GITHUB_NS, 'github:{repo}:pr_review_comment:{id}')
      gitlab.mr: uuidv5(GITLAB_NS, 'gitlab:{project}:mr:{iid}')
      gitlab.note: uuidv5(GITLAB_NS, 'gitlab:{project}:note:{id}')
      notion.page: page_id (already a Notion UUID)
      notion.heading: uuidv5(NOTION_NS, 'notion:heading:{page_id}:{block_id}')
      notion.thread: discussion_id (already a Notion UUID)
      notion.comment: comment_id (already a Notion UUID)
    """
    provider: str
    """Which provider this row originated from. Determines which per-provider table to consult for the raw payload."""
    kind: str
    """Row category as displayed in the Kind column. Drives the row-type filter (chat: vs message:) and the icon.

    Per-provider mapping:
      anthropic.chat: 'Chat'
      anthropic.message.human: 'User Input'
      anthropic.message.assistant: 'LLM Response'
      anthropic.block.thinking: 'LLM Thinking'
      anthropic.block.tool_*: 'Tool Call'
      openai.chat: 'Chat'
      openai.message.user: 'User Input'
      openai.message.assistant.thoughts|reasoning_recap: 'LLM Thinking'
      openai.message.assistant.*: 'LLM Response'
      openai.message.system|*: 'Tool Call'
      slack.thread: 'Slack Thread'
      slack.message: 'Slack Message'
      github.pr: 'GitHub PR'
      github.issue_comment: 'GitHub PR Comment'
      github.pr_review: 'GitHub Review'
      github.pr_review_comment: 'GitHub Review Comment'
      gitlab.mr: 'GitLab MR'
      gitlab.note: 'GitLab Discussion Note'
      notion.page: 'Notion Page' (or 'Notion Database' for collection_view_page)
      notion.heading.h1: 'Notion Heading 1'
      notion.heading.h2: 'Notion Heading 2'
      notion.heading.h3: 'Notion Heading 3'
      notion.thread: 'Notion Comment Thread'
      notion.comment: 'Notion Comment'
    """
    source_label: str
    """Human-friendly provider label shown in the Source column.

    Per-provider mapping:
      anthropic: 'Claude'
      openai: 'ChatGPT'
      slack: 'Slack'
      github: 'GitHub'
      gitlab: 'GitLab'
      notion: 'Notion'
    """
    when_ts: str
    """ISO-8601 timestamp with explicit offset, used for global sort and before:/after: filters. Synthesized for blocks/messages without their own timestamp by bumping microseconds off the parent's timestamp so within-conversation order stays stable.

    Per-provider mapping:
      anthropic.chat: IFNULL(created_at, updated_at)
      anthropic.message: messages.created_at
      anthropic.block: blocks.start_timestamp OR bump_micros(parent_msg.created_at, block_index+1)
      openai.chat: IFNULL(create_time, update_time)
      openai.message: messages.create_time OR bump_micros(parent_conv.create_time, msg_idx+1)
      slack.message: slack_messages.ts (Slack ts is unix-seconds-with-fractional, formatted as ISO-8601 in UTC)
      github.pr: pull_request.updated_at OR created_at
      github.comment: comment.created_at
      gitlab.mr: merge_request.updated_at OR created_at
      gitlab.note: note.created_at
      notion.page: block.last_edited_time (Notion ms epoch, formatted ISO-8601 UTC)
      notion.heading: parent_page.last_edited_time (headings inherit page's last_edited_time)
      notion.thread: first comment.created_time
      notion.comment: comment.created_time
    """
    author: str | None
    """Display name of the message author. For LLM responses this is typically the model slug; for user inputs, the account; for Slack, the user real_name.

    Per-provider mapping:
      anthropic.chat: ''
      anthropic.message.human: account_uuid
      anthropic.message.assistant: conversation.raw_json.model OR sender
      openai.message.user: account_id
      openai.message.assistant: model_slug OR role
      slack.message: users.real_name OR users.name
      github: comment.user.login OR pull_request.user.login
      gitlab: note.author.username OR merge_request.author.username
      notion.page: notion_user.name for block.last_edited_by_id (or created_by for headings)
      notion.heading: notion_user.name for parent_page.last_edited_by_id
      notion.thread: notion_user.name for first comment.created_by_id
      notion.comment: notion_user.name for comment.created_by_id
    """
    account: str | None
    """Account identifier (provider-native). Drives the account: filter.

    Per-provider mapping:
      anthropic: anthropic_conversations.account_uuid
      openai: openai_conversations.account_id
      slack: slack_workspaces.team_id
      github: self_identity.viewer.login (the host account that fetched the data)
      gitlab: self_identity.current_user.username
      notion: notion_space.name (workspace name; one per ingest)
    """
    project: str | None
    """Project identifier. For anthropic this is the project UUID; for github/gitlab this is the repo full name (e.g. 'owner/repo' or 'group/.../project_path'). Null for providers without a project notion (openai, slack).

    Per-provider mapping:
      anthropic: anthropic_conversations.project_uuid
      openai: null
      slack: null
      github: pull_request.base.repo.full_name (e.g. 'enterprise-d/replicator-firmware')
      gitlab: merge_request.references.full or project_path (e.g. 'enterprise-d/holodeck')
      notion: null (Notion does not have a per-page project notion; workspace lives in `account`)
    """
    channel: str | None
    """Slack channel display name (e.g. 'bridge', 'engineering'). Null for non-Slack rows. Drives the Channel column and a future channel: filter.

    Per-provider mapping:
      anthropic: null
      openai: null
      slack: slack_channels.channel_name
      github: null
      gitlab: null
    """
    conversation_name: str | None
    """Human-readable parent conversation title — drives the Conversation Name grid column. For Chat rows this duplicates the row's own title; for messages/blocks it carries the parent thread's title so each grid row stands alone without a join.

    Per-provider mapping:
      anthropic: anthropic_conversations.name
      openai: openai_conversations.title
      slack: slack_channels.channel_name + thread root snippet
      github: pull_request.title (carried onto every child comment/review row)
      gitlab: merge_request.title (carried onto every child note row)
      notion.page: block.properties.title (plain-text join)
      notion.heading: parent_page.properties.title
      notion.thread: parent_page.properties.title
      notion.comment: parent_page.properties.title
    """
    conversation_uuid: str
    """Parent conversation / thread UUID. For Chat / Slack Thread rows this equals `uuid`. For Message / block rows it points at the parent so the chat preview pane knows which thread to open.

    Per-provider mapping:
      anthropic.chat: = uuid (conversation_uuid)
      anthropic.message: messages.conversation_uuid
      anthropic.block: parent_message.conversation_uuid
      openai.chat: = uuid (conversation_id)
      openai.message: messages.conversation_id
      slack.thread: = uuid (thread root uuid)
      slack.message: thread root uuid
      github.pr: = uuid (PR uuid)
      github.comment: parent PR uuid
      gitlab.mr: = uuid (MR uuid)
      gitlab.note: parent MR uuid
      notion.page: = uuid (page_id)
      notion.heading: parent page_id
      notion.thread: = uuid (discussion_id)
      notion.comment: parent discussion_id
    """
    message_index: int | None
    """Zero-based index of this message within its conversation, in the same order the QMD file renders messages. Used by ChatPreviewPane to scroll to and highlight the clicked message via `[data-msg-index="{index}"]`. Null for Chat / Slack Thread rows."""
    entire_chat: str
    """Path used by the row to open the full thread in the right-hand preview. Today: `/chat/{conversation_uuid}`."""
    text: str
    """Full searchable body for this row. The Rust backend computes the displayed snippet from `text` + the user's free-text needle at query time, so we store the full body here rather than a pre-truncated snippet.

    Per-provider mapping:
      anthropic.chat: summary OR name
      anthropic.message: messages.text
      anthropic.block: blocks.text OR raw_json.thinking OR type
      openai.chat: title
      openai.message: messages.text
      slack.thread: root message text
      slack.message: messages.text (with mention/emoji rendering)
      github.pr: pull_request.title + body
      github.comment: comment.body
      gitlab.mr: merge_request.title + description
      gitlab.note: note.body
      notion.page: page title + full plain-text body of all child blocks (recursive)
      notion.heading: heading block's plain-text title
      notion.thread: concatenated plain-text of every comment in the discussion
      notion.comment: comment.text rendered to plain text
    """
    slack_link: str | None
    """Deep link of the form `slack://channel?team={team_id}&id={channel_id}&message={ts}` (or the https equivalent). Populated only for Slack rows; drives the 'Open in Slack' right-click context menu item."""
    qmd_path: str | None
    """Path to the rendered Markdown file for this row's conversation/thread, relative to the data root. All paths are rooted under `rendered_md/<provider>/...`. Set on every row (chat-level rows point at their own .md; message/block rows inherit their parent thread's). The chat preview pane uses this to load the conversation directly — no glob, no frontmatter scan. (Column name retained as `qmd_path` for historical reasons.)

    Per-provider mapping:
      anthropic: rendered_md/anthropic/{account_uuid}/llm_chats/{conversation_uuid}__{slug(name)}.md
      openai: rendered_md/openai/{account_id|unknown}/llm_chats/{conversation_id}__{slug(title)}.md
      slack: rendered_md/slack/{team_id}/{channel_name}/threads/{thread_uuid}__{slug(root_text[:80])}.md
      github: rendered_md/github/{owner}/{repo}/pr-{number}__{slug(title)}/index.md (PR), or .../threads/{thread_uuid}__{slug}.md (comment threads)
      gitlab: rendered_md/gitlab/{group}/{project}/mr-{iid}__{slug(title)}/index.md (MR), or .../threads/{discussion_uuid}__{slug}.md (discussion threads)
      notion: rendered_md/notion/{space_slug}__{short_id}/{...nested page slugs}/{page_slug}__{short_id}.md (pages + headings); .../comments/{thread_short_id}__{snippet}.md (comment threads)
    """
    source_url: str | None
    """Canonical URL pointing back to the original source on the provider's web UI. For GitHub/GitLab this is the html_url/web_url of the PR/MR or comment; null for providers without a stable public link.

    Per-provider mapping:
      github.pr: pull_request.html_url
      github.comment: comment.html_url
      gitlab.mr: merge_request.web_url
      gitlab.note: merge_request.web_url + '#note_' + note.id
    """
    git_sha: str | None
    """Git commit SHA associated with the row, used to reconstruct exact source state. For PRs/MRs this is the head SHA at the time of ingest; for review/diff comments it's the commit the comment is anchored to.

    Per-provider mapping:
      github.pr: pull_request.head.sha
      github.pr_review: review.commit_id
      github.pr_review_comment: comment.commit_id OR comment.original_commit_id
      gitlab.mr: merge_request.sha (head)
      gitlab.note: note.position.head_sha (if diff note) else null
    """
    external_id: str | None
    """Provider-native primary identifier for this entity (e.g. numeric GitHub/GitLab id, PR number). Preserved alongside our uuid so we can round-trip back to the provider's API.

    Per-provider mapping:
      github.pr: pull_request.number
      github.issue_comment: comment.id
      github.pr_review: review.id
      github.pr_review_comment: comment.id
      gitlab.mr: merge_request.iid
      gitlab.note: note.id
    """
    notion_page_uuid: str | None
    """Notion-only. UUID of the page this row belongs to. For page rows this equals `uuid`; for heading / comment thread / comment rows it points at the containing page so the grid can filter every row that lives in a given document. Null for non-Notion rows."""
    notion_block_uuid: str | None
    """Notion-only. UUID of the specific block this row is anchored to. For heading rows this is the heading block; for comment-thread rows it is the block the discussion is attached to (`discussion.parent_id` when parent_table='block'); for individual comment rows it is the same as the parent thread's block. Null for page-level rows and non-Notion rows."""
    document_uuid: str | None
    """FK into the `documents` table — every renderable document (conversation, thread, page, …) gets one row in `documents`, and every grid_row that participates in that document points at it. Many-to-1. Nullable today because the column is being introduced ahead of the producer-side population pass (see plan-ui-driven-sync.md, Phase C); will become NOT NULL once every renderer emits it. Drives incremental re-render (skip if `documents.row_set_hash` unchanged) and per-document re-ingest."""


TABLES: dict[str, str] = {
    "grid_rows": "GridRow",
}


# Portable CREATE TABLE statements for every table this schema defines.
# Same SQL subset accepted by Dolt, MySQL, and SQLite.
DDL: list[str] = [
    """
CREATE TABLE IF NOT EXISTS grid_rows (
    uuid VARCHAR(96) NOT NULL,
    provider VARCHAR(32) NOT NULL,
    kind VARCHAR(32) NOT NULL,
    source_label VARCHAR(32) NOT NULL,
    when_ts VARCHAR(40) NOT NULL,
    author VARCHAR(255),
    account VARCHAR(96),
    project VARCHAR(96),
    channel VARCHAR(255),
    conversation_name VARCHAR(512),
    conversation_uuid VARCHAR(96) NOT NULL,
    message_index INT,
    entire_chat VARCHAR(255) NOT NULL,
    text LONGTEXT NOT NULL,
    slack_link VARCHAR(512),
    qmd_path VARCHAR(512),
    source_url VARCHAR(1024),
    git_sha VARCHAR(64),
    external_id VARCHAR(128),
    notion_page_uuid VARCHAR(96),
    notion_block_uuid VARCHAR(96),
    document_uuid VARCHAR(96),
    PRIMARY KEY (uuid)
)
    """,
]


# Column names per table, in declaration order.
COLUMNS: dict[str, list[str]] = {
    "grid_rows": [
        "uuid",
        "provider",
        "kind",
        "source_label",
        "when_ts",
        "author",
        "account",
        "project",
        "channel",
        "conversation_name",
        "conversation_uuid",
        "message_index",
        "entire_chat",
        "text",
        "slack_link",
        "qmd_path",
        "source_url",
        "git_sha",
        "external_id",
        "notion_page_uuid",
        "notion_block_uuid",
        "document_uuid",
    ],
}


# Per-column max byte length for VARCHAR(N) columns. Writers should
# truncate over-long values before INSERT — Dolt/MySQL reject the
# whole batch otherwise. Columns with TEXT/LONGTEXT types are absent
# from this map (effectively unbounded for our purposes).
MAX_LENGTHS: dict[str, dict[str, int]] = {
    "grid_rows": {
        "uuid": 96,
        "provider": 32,
        "kind": 32,
        "source_label": 32,
        "when_ts": 40,
        "author": 255,
        "account": 96,
        "project": 96,
        "channel": 255,
        "conversation_name": 512,
        "conversation_uuid": 96,
        "entire_chat": 255,
        "slack_link": 512,
        "qmd_path": 512,
        "source_url": 1024,
        "git_sha": 64,
        "external_id": 128,
        "notion_page_uuid": 96,
        "notion_block_uuid": 96,
        "document_uuid": 96,
    },
}
