"""AUTOGENERATED by schemas/codegen.py — do not edit. Source: documents.schema.json."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class DocumentRow:
    """One row in the `documents` table. Source of truth for `<root>/rendered_md/<...>.md` cache invalidation: ingest computes a fresh `row_set_hash` from the canonical grid_row tuples for this document and compares it to the stored value; on mismatch the renderer re-emits the file and bumps `rendered_at`. A bump to `renderer_version` invalidates every cache entry at once."""

    document_uuid: str
    """Stable document identifier. For providers whose native id is already a UUID (Anthropic conversation_uuid, Notion page_id) we reuse it verbatim; for ts-keyed providers (Slack threads) we synthesize a UUIDv5 from the same canonical tuple `grid_rows.uuid` uses. Must be deterministic so re-ingest is idempotent."""
    source_name: str
    """`sources[].name` from `config.yaml` that produced this document. Lets the sync UI show per-source delta counts and the worker scope re-renders to a single source."""
    provider: str
    """Denormalized provider tag, matches `grid_rows.provider` for the rows that point at this document. Stored here so the documents table is queryable without a join when filtering the sync page."""
    kind: str
    """Document-level category. Distinct from `grid_rows.kind` (which is per-row); this is the shape of the rendered markdown file."""
    title: str | None
    """Human-readable title — same value the renderer puts in the markdown frontmatter / page header. Nullable for sources whose entities don't have an authored title (e.g. early Slack threads); the renderer falls back to a snippet of the first message."""
    created_at: str | None
    """Earliest authored timestamp for content in this document (ISO-8601 with explicit offset, per AGENTS.md). Sourced from the underlying provider — not when we ingested it."""
    updated_at: str | None
    """Latest authored timestamp for content in this document (ISO-8601 with explicit offset). Drives the sync page's `Last updated` column."""
    md_path: str | None
    """Path to the rendered markdown file, relative to `<root>/rendered_md/`. NULL until the renderer has produced output. The backend's `/api/chat/{uuid}` endpoint resolves this column to find the file to serve."""
    row_set_hash: str
    """SHA-256 (hex) over the canonical tuple list of grid_rows that feed this document — message texts, authors, timestamps, attachments. Computed by ingest; if it matches the stored value and `renderer_version` is unchanged, the renderer skips this document. The canonical tuple definition is part of the renderer contract; bump `renderer_version` if you change it."""
    renderer_version: str
    """Opaque version string for the renderer that produced `md_path`. Bumping this value (typically when the markdown layout or templating changes) invalidates every documents row's cache and forces a global re-render on the next ingest."""
    rendered_at: str | None
    """When `md_path` was last written (ISO-8601 with explicit local offset, per AGENTS.md). NULL before the first render."""


TABLES: dict[str, str] = {
    "documents": "DocumentRow",
}


# Portable CREATE TABLE statements for every table this schema defines.
# Same SQL subset accepted by Dolt, MySQL, and SQLite.
DDL: list[str] = [
    """
CREATE TABLE IF NOT EXISTS documents (
    document_uuid VARCHAR(96) NOT NULL,
    source_name VARCHAR(64) NOT NULL,
    provider VARCHAR(32) NOT NULL,
    kind VARCHAR(32) NOT NULL,
    title VARCHAR(512),
    created_at VARCHAR(40),
    updated_at VARCHAR(40),
    md_path VARCHAR(1024),
    row_set_hash CHAR(64) NOT NULL,
    renderer_version VARCHAR(32) NOT NULL,
    rendered_at VARCHAR(40),
    PRIMARY KEY (document_uuid)
)
    """,
]


# Column names per table, in declaration order.
COLUMNS: dict[str, list[str]] = {
    "documents": [
        "document_uuid",
        "source_name",
        "provider",
        "kind",
        "title",
        "created_at",
        "updated_at",
        "md_path",
        "row_set_hash",
        "renderer_version",
        "rendered_at",
    ],
}


# Per-column max byte length for VARCHAR(N) columns. Writers should
# truncate over-long values before INSERT — Dolt/MySQL reject the
# whole batch otherwise. Columns with TEXT/LONGTEXT types are absent
# from this map (effectively unbounded for our purposes).
MAX_LENGTHS: dict[str, dict[str, int]] = {
    "documents": {
        "document_uuid": 96,
        "source_name": 64,
        "provider": 32,
        "kind": 32,
        "title": 512,
        "created_at": 40,
        "updated_at": 40,
        "md_path": 1024,
        "renderer_version": 32,
        "rendered_at": 40,
    },
}
