"""AUTOGENERATED by schemas/codegen.py — do not edit. Source: download_runs.schema.json."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class DownloadRunRow:
    """One row per downloader invocation. The downloader inserts at start; the same downloader stamps `finished_at` on success; the ingest pipeline stamps `ingested_at` + `doc_uuids_touched` after it consumes the raw file. Rows are kept indefinitely so we can answer `which sync brought in this document?`"""

    id: str
    """UUIDv4 generated by the downloader at run start. Used as the FK on any future per-document provenance tracking."""
    source_name: str
    """`sources[].name` from `config.yaml`. Joinable to `sync_jobs.source_name` and `documents.source_name`."""
    raw_path: str
    """Path to the raw file produced by this run, relative to `<root>/raw/`. The file is named `<ISO-timestamp>.<ext>` so disk listing is chronologically sorted."""
    kind: str
    """`full` = complete snapshot of everything the downloader could see (used as a periodic self-healing checkpoint); `delta` = items new/changed since the previous run, using the last successful run's `finished_at` as the `since` watermark. Default mode is `delta`; `--full` overrides."""
    started_at: str
    """When the downloader began this run (ISO-8601 with explicit local offset, per AGENTS.md)."""
    finished_at: str | None
    """When the downloader finished successfully (ISO-8601 with explicit offset). NULL means the run is either still in progress or it crashed; ingest treats NULL as `do not consume yet`."""
    ingested_at: str | None
    """When ingest finished consuming `raw_path` (ISO-8601 with explicit offset). NULL until then. Ingest's work queue is `SELECT ... WHERE finished_at IS NOT NULL AND ingested_at IS NULL`."""
    doc_uuids_touched: str | None
    """JSON array of `documents.document_uuid` values that this run produced changes for. Populated by ingest when it sets `ingested_at`. Useful for `which sync surfaced this thread?` provenance queries; not used by the hot path."""


TABLES: dict[str, str] = {
    "download_runs": "DownloadRunRow",
}


# Portable CREATE TABLE statements for every table this schema defines.
# Same SQL subset accepted by Dolt, MySQL, and SQLite.
DDL: list[str] = [
    """
CREATE TABLE IF NOT EXISTS download_runs (
    id VARCHAR(36) NOT NULL,
    source_name VARCHAR(64) NOT NULL,
    raw_path VARCHAR(1024) NOT NULL,
    kind VARCHAR(8) NOT NULL,
    started_at VARCHAR(40) NOT NULL,
    finished_at VARCHAR(40),
    ingested_at VARCHAR(40),
    doc_uuids_touched JSON,
    PRIMARY KEY (id)
)
    """,
]


# Column names per table, in declaration order.
COLUMNS: dict[str, list[str]] = {
    "download_runs": [
        "id",
        "source_name",
        "raw_path",
        "kind",
        "started_at",
        "finished_at",
        "ingested_at",
        "doc_uuids_touched",
    ],
}


# Per-column max byte length for VARCHAR(N) columns. Writers should
# truncate over-long values before INSERT — Dolt/MySQL reject the
# whole batch otherwise. Columns with TEXT/LONGTEXT types are absent
# from this map (effectively unbounded for our purposes).
MAX_LENGTHS: dict[str, dict[str, int]] = {
    "download_runs": {
        "id": 36,
        "source_name": 64,
        "raw_path": 1024,
        "kind": 8,
        "started_at": 40,
        "finished_at": 40,
        "ingested_at": 40,
    },
}
