//! Cross-provider **Render-and-index-md → Load** contract — the "index"
//! layer.
//!
//! Every provider's render-and-index-md step emits one `.grid_rows.json` sidecar
//! per rendered markdown by calling [`emit_sidecar`]. The provider-
//! agnostic Load step reads them back as [`Sidecar`] and upserts the
//! rows into the backend index. Both sides import from this crate so
//! the shape can't drift.
//!
//! Sidecar wire format:
//!
//! ```jsonc
//! {
//!   "header": {
//!     "markdown_uuid": "…",            // primary key for the rendered .md
//!     "source_fingerprint": "…",       // hash of upstream payload
//!     "render_version": 1              // renderer-side schema stamp
//!   },
//!   "rows": [GridRow, …],
//!   "edges": [EdgeRow, …]              // optional; omitted when empty
//! }
//! ```
//!
//! `GridRow` and `EdgeRow` are re-exported from `frankweiler-schema`
//! (the autogenerated row types whose SQL DDL backs the
//! `backend_index.doltlite_db` tables). Re-exporting them here means
//! a provider's render code only imports `frankweiler_index_lib`:
//!
//! ```ignore
//! use frankweiler_index_lib::{emit_sidecar, EdgeRow, GridRow};
//! ```

use std::path::Path;

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

pub use frankweiler_schema::edges::EdgeRow;
pub use frankweiler_schema::grid_rows::GridRow;

/// Header for the per-markdown sidecar. Carried in the on-disk
/// `.grid_rows.json` file and consumed by the Load step's
/// fingerprint-based skip check.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SidecarHeader {
    /// Stable id for the rendered `.md` this sidecar describes. Slack
    /// Render sets this to the thread uuid; per-period providers
    /// (beeper, signal) set it to a `(room, period)` UUIDv5;
    /// whole-conversation providers (notion page, github PR, …) reuse
    /// their native uuid.
    pub markdown_uuid: String,
    /// Blake3 / SHA hash of the upstream payload(s) that produced this
    /// document. Load skips re-applying rows when the existing row's
    /// fingerprint matches.
    pub source_fingerprint: String,
    /// Renderer-side schema stamp. Bumped by the provider when the
    /// rendered markdown / row shape changes in a way that should
    /// invalidate previously-rendered docs.
    pub render_version: u32,
}

/// Owned sidecar — the on-disk wire shape. Use this when **reading**
/// a sidecar back. When **writing** from a provider's render code,
/// prefer [`emit_sidecar`] which avoids the intermediate `Vec` clones.
#[derive(Debug, Serialize, Deserialize)]
pub struct Sidecar {
    pub header: SidecarHeader,
    pub rows: Vec<GridRow>,
    /// Outgoing edges originating from this markdown
    /// (`src_markdown_uuid == header.markdown_uuid`). Older sidecars
    /// pre-dating the edges table omit the field; serde default yields
    /// an empty Vec so the Load step skips edge writes. We also skip
    /// serializing when empty so renderers that don't emit edges
    /// produce byte-identical sidecars to the pre-edges era — important
    /// for golden tests and for incremental cache stability.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub edges: Vec<EdgeRow>,
}

/// Borrowing serializer for the write path. Mirrors [`Sidecar`]'s
/// serde shape (including the `skip_serializing_if` on `edges`) so
/// `emit_sidecar` produces byte-identical output without cloning
/// every `GridRow` / `EdgeRow`.
#[derive(Serialize)]
struct SidecarRef<'a> {
    header: SidecarHeader,
    rows: &'a [GridRow],
    #[serde(skip_serializing_if = "slice_is_empty")]
    edges: &'a [EdgeRow],
}

fn slice_is_empty<T>(s: &&[T]) -> bool {
    s.is_empty()
}

/// Write one provider's `.grid_rows.json` sidecar to disk in the
/// canonical shape. Single helper used by every provider so the
/// header field names, the empty-edges skip, and the pretty-printing
/// can't drift between providers.
///
/// `sidecar_path` is typically the markdown's path with the `.md`
/// extension swapped for `.grid_rows.json`.
pub fn emit_sidecar(
    sidecar_path: &Path,
    markdown_uuid: &str,
    source_fingerprint: &str,
    render_version: u32,
    rows: &[GridRow],
    edges: &[EdgeRow],
) -> Result<()> {
    let payload = SidecarRef {
        header: SidecarHeader {
            markdown_uuid: markdown_uuid.to_string(),
            source_fingerprint: source_fingerprint.to_string(),
            render_version,
        },
        rows,
        edges,
    };
    let json = serde_json::to_string_pretty(&payload)
        .with_context(|| format!("serialize sidecar {}", sidecar_path.display()))?;
    std::fs::write(sidecar_path, json)
        .with_context(|| format!("write sidecar {}", sidecar_path.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn empty_row(uuid: &str) -> GridRow {
        GridRow {
            uuid: uuid.into(),
            provider: "test".into(),
            kind: "Test".into(),
            source_label: "Test".into(),
            when_ts: Some("2026-01-01T00:00:00+00:00".into()),
            author: None,
            account: None,
            project: None,
            org_uuid: None,
            org_name: None,
            channel: None,
            conversation_name: None,
            conversation_uuid: uuid.into(),
            message_index: None,
            entire_chat: format!("/chat/{uuid}"),
            text: String::new(),
            slack_link: None,
            qmd_path: None,
            source_url: None,
            git_sha: None,
            external_id: None,
            notion_page_uuid: None,
            notion_block_uuid: None,
            markdown_uuid: Some(uuid.into()),
        }
    }

    #[test]
    fn emit_round_trips_through_sidecar() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("doc.grid_rows.json");
        let rows = vec![empty_row("u-1")];
        emit_sidecar(&path, "md-1", "fp-1", 7, &rows, &[]).unwrap();
        let raw = std::fs::read_to_string(&path).unwrap();
        let parsed: Sidecar = serde_json::from_str(&raw).unwrap();
        assert_eq!(parsed.header.markdown_uuid, "md-1");
        assert_eq!(parsed.header.source_fingerprint, "fp-1");
        assert_eq!(parsed.header.render_version, 7);
        assert_eq!(parsed.rows.len(), 1);
        assert!(parsed.edges.is_empty());
        // Empty edges must be omitted from the serialized form so we
        // stay byte-identical with the pre-edges era for golden tests.
        assert!(!raw.contains("\"edges\""));
    }

    #[test]
    fn empty_edges_are_skipped_owned_too() {
        // The owned `Sidecar` must serialize the same way as the
        // borrowing writer — both ends of the contract round-trip.
        let s = Sidecar {
            header: SidecarHeader {
                markdown_uuid: "md".into(),
                source_fingerprint: "fp".into(),
                render_version: 1,
            },
            rows: vec![empty_row("u")],
            edges: Vec::new(),
        };
        let json = serde_json::to_string(&s).unwrap();
        assert!(!json.contains("\"edges\""));
    }
}
