load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

exports_files(["Cargo.toml"])

rust_library(
    name = "datalib_tauri_backend",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "datalib_tauri_backend",
    edition = "2021",
    visibility = ["//datalib:__subpackages__"],
    deps = [
        "//datalib/backend/core:datalib_core",
        "//datalib/backend/schema:datalib_schema",
    ],
)

rust_test(
    name = "tauri_backend_unittests",
    size = "small",
    crate = ":datalib_tauri_backend",
    edition = "2021",
)
