"""Tiny codegen driver: JSON Schema -> Rust / Python / TypeScript types.

v0 keeps this hand-rolled and intentionally small. We only handle the subset of
JSON Schema we actually use in `anthropic.schema.json`: object types with
required+properties; primitives string/integer/number/boolean; nullable via
["T", "null"]; date-time formatted strings; enums of strings; $ref to local
definitions.

Usage:
    python codegen.py <schema.json> --rust <out.rs>
                                    --python <out.py>
                                    --typescript <out.ts>
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def _is_nullable(t: Any) -> tuple[bool, Any]:
    if isinstance(t, list) and "null" in t:
        rest = [x for x in t if x != "null"]
        return True, rest[0] if len(rest) == 1 else rest
    return False, t


def _resolve_ref(schema: dict, ref: str) -> tuple[str, dict]:
    assert ref.startswith("#/definitions/"), ref
    name = ref.removeprefix("#/definitions/")
    return name, schema["definitions"][name]


def _ts_type(prop: dict, schema: dict) -> str:
    if "$ref" in prop:
        name, _ = _resolve_ref(schema, prop["$ref"])
        return name
    nullable, t = _is_nullable(prop.get("type"))
    if "enum" in prop:
        body = " | ".join(json.dumps(v) for v in prop["enum"])
        return f"({body})" + (" | null" if nullable else "")
    mapping = {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
    }
    base = mapping.get(t, "unknown")
    return base + (" | null" if nullable else "")


def _rust_type(prop: dict, schema: dict) -> str:
    if "$ref" in prop:
        name, _ = _resolve_ref(schema, prop["$ref"])
        return name
    nullable, t = _is_nullable(prop.get("type"))
    if "enum" in prop:
        base = "String"
    else:
        base = {
            "string": "String",
            "integer": "i64",
            "number": "f64",
            "boolean": "bool",
        }.get(t, "serde_json::Value")
    return f"Option<{base}>" if nullable else base


def _py_type(prop: dict, schema: dict) -> str:
    if "$ref" in prop:
        name, _ = _resolve_ref(schema, prop["$ref"])
        return name
    nullable, t = _is_nullable(prop.get("type"))
    if "enum" in prop:
        base = "str"
    else:
        base = {
            "string": "str",
            "integer": "int",
            "number": "float",
            "boolean": "bool",
        }.get(t, "object")
    return f"{base} | None" if nullable else base


def emit_typescript(schema: dict) -> str:
    out = [
        "// AUTOGENERATED by schemas/codegen.py — do not edit.",
        "// Source: anthropic.schema.json",
        "",
    ]
    for name, defn in schema["definitions"].items():
        out.append(f"export interface {name} {{")
        required = set(defn.get("required", []))
        for prop_name, prop in defn.get("properties", {}).items():
            opt = "" if prop_name in required else "?"
            out.append(f"  {prop_name}{opt}: {_ts_type(prop, schema)};")
        out.append("}")
        out.append("")
    out.append("export const TABLES = {")
    for table, ref in schema.get("tables", {}).items():
        type_name = ref.removeprefix("#/definitions/")
        out.append(f"  {json.dumps(table)}: {json.dumps(type_name)},")
    out.append("} as const;")
    out.append("")
    return "\n".join(out)


def emit_rust(schema: dict) -> str:
    out = [
        "// AUTOGENERATED by schemas/codegen.py — do not edit.",
        "// Source: anthropic.schema.json",
        "",
        "use serde::{Deserialize, Serialize};",
        "",
    ]
    rust_keywords = {
        "type",
        "match",
        "ref",
        "move",
        "fn",
        "let",
        "mut",
        "use",
        "mod",
        "self",
        "super",
        "trait",
        "impl",
        "as",
        "where",
        "while",
        "loop",
    }
    for name, defn in schema["definitions"].items():
        out.append("#[derive(Debug, Clone, Serialize, Deserialize)]")
        out.append(f"pub struct {name} {{")
        for prop_name, prop in defn.get("properties", {}).items():
            field = f"r#{prop_name}" if prop_name in rust_keywords else prop_name
            out.append(f"    pub {field}: {_rust_type(prop, schema)},")
        out.append("}")
        out.append("")
    out.append("pub const TABLES: &[(&str, &str)] = &[")
    for table, ref in schema.get("tables", {}).items():
        type_name = ref.removeprefix("#/definitions/")
        out.append(f'    ("{table}", "{type_name}"),')
    out.append("];")
    out.append("")
    return "\n".join(out)


def emit_python(schema: dict) -> str:
    out = [
        '"""AUTOGENERATED by schemas/codegen.py — do not edit."""',
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "",
    ]
    for name, defn in schema["definitions"].items():
        out.append("@dataclass")
        out.append(f"class {name}:")
        props = list(defn.get("properties", {}).items())
        if not props:
            out.append("    pass")
        for prop_name, prop in props:
            out.append(f"    {prop_name}: {_py_type(prop, schema)}")
        out.append("")
    out.append("TABLES: dict[str, str] = {")
    for table, ref in schema.get("tables", {}).items():
        type_name = ref.removeprefix("#/definitions/")
        out.append(f'    "{table}": "{type_name}",')
    out.append("}")
    out.append("")
    return "\n".join(out)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("schema", type=Path)
    ap.add_argument("--rust", type=Path)
    ap.add_argument("--python", type=Path)
    ap.add_argument("--typescript", type=Path)
    args = ap.parse_args()

    schema = json.loads(args.schema.read_text())
    if args.rust:
        args.rust.write_text(emit_rust(schema))
    if args.python:
        args.python.write_text(emit_python(schema))
    if args.typescript:
        args.typescript.write_text(emit_typescript(schema))


if __name__ == "__main__":
    main()
