//! WhatsApp's "backup encryption" key derivation.

use hmac::{Hmac, KeyInit, Mac};
use sha2::Sha256;

type HmacSha256 = Hmac<Sha256>;

const BACKUP_ENCRYPTION_INFO: &[u8] = b"backup encryption";

pub fn derive_backup_encryption_key(root_key: &[u8; 32]) -> [u8; 32] {
    // PRK = HMAC-SHA256(zero salt, root_key)
    let mut mac = HmacSha256::new_from_slice(&[0u8; 32]).expect("HMAC accepts any key length");
    mac.update(root_key);
    let prk = mac.finalize().into_bytes();

    // T(1) = HMAC-SHA256(PRK, info || 0x01)
    let mut mac = HmacSha256::new_from_slice(&prk).expect("HMAC accepts any key length");
    mac.update(BACKUP_ENCRYPTION_INFO);
    mac.update(&[0x01]);
    let t1 = mac.finalize().into_bytes();

    let mut out = [0u8; 32];
    out.copy_from_slice(&t1);
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Cross-check against the `encryptionloop` reference in
    /// `wa-crypt-tools/lib/utils.py` (the upstream Python). Input
    /// `root_key` is reproducible (`[0x42; 32]`) so this vector is
    /// stable; output was computed once by running the Python:
    #[test]
    fn matches_python_reference_for_all_42s() {
        let root = [0x42u8; 32];
        let aes_key = derive_backup_encryption_key(&root);
        // Generated by the Python one-liner above:
        let expected = hex32("327eae6160f3a0ff6e37d823b9d79f01f1953c501cf1fd7b7494bfed29228395");
        assert_eq!(
            aes_key, expected,
            "derived key differs from Python encryptionloop output"
        );
    }

    fn hex32(s: &str) -> [u8; 32] {
        let mut out = [0u8; 32];
        for i in 0..32 {
            out[i] = u8::from_str_radix(&s[i * 2..i * 2 + 2], 16).unwrap();
        }
        out
    }
}
