//! WhatsApp's "backup encryption" key derivation.
//!
//! The 32-byte value in `encrypted_backup.key` (the file pulled from a
//! phone, or its hex representation in `WHATSAPP_BACKUP_DECRYPTION_KEY`)
//! is the *root* key, not the AES key. WhatsApp derives the AES-256-GCM
//! key for crypt15 backups from the root key with a one-iteration
//! HMAC-SHA256 KDF:
//!
//! ```text
//!   prk    = HMAC-SHA256(salt=0^32, msg=root_key)
//!   T(1)   = HMAC-SHA256(key=prk, msg="backup encryption" || 0x01)
//!   aes_key = T(1)
//! ```
//!
//! That's essentially HKDF-SHA256 with a zero salt, info =
//! `"backup encryption"`, and output length 32 (so the counter byte is
//! just `0x01`). The "metadata encryption" and "metadata authentication"
//! sub-keys WhatsApp uses for Google-Drive E2E metadata are derived the
//! same way with different `info` strings; we don't need them for
//! local backup decrypt.

use hmac::{Hmac, Mac};
use sha2::Sha256;

type HmacSha256 = Hmac<Sha256>;

const BACKUP_ENCRYPTION_INFO: &[u8] = b"backup encryption";

/// Derive the AES-256 key for crypt15 message-DB decryption from the
/// 32-byte root key. Single-iteration HKDF-style construction.
pub fn derive_backup_encryption_key(root_key: &[u8; 32]) -> [u8; 32] {
    // PRK = HMAC-SHA256(zero salt, root_key)
    let mut mac = HmacSha256::new_from_slice(&[0u8; 32]).expect("HMAC accepts any key length");
    mac.update(root_key);
    let prk = mac.finalize().into_bytes();

    // T(1) = HMAC-SHA256(PRK, info || 0x01)
    let mut mac = HmacSha256::new_from_slice(&prk).expect("HMAC accepts any key length");
    mac.update(BACKUP_ENCRYPTION_INFO);
    mac.update(&[0x01]);
    let t1 = mac.finalize().into_bytes();

    let mut out = [0u8; 32];
    out.copy_from_slice(&t1);
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Cross-check against the `encryptionloop` reference in
    /// `wa-crypt-tools/lib/utils.py` (the upstream Python). Input
    /// `root_key` is reproducible (`[0x42; 32]`) so this vector is
    /// stable; output was computed once by running the Python:
    ///
    /// ```python
    /// from wa_crypt_tools.lib.utils import encryptionloop
    /// encryptionloop(first_iteration_data=bytes([0x42]*32),
    ///                message=b'backup encryption', output_bytes=32).hex()
    /// ```
    #[test]
    fn matches_python_reference_for_all_42s() {
        let root = [0x42u8; 32];
        let aes_key = derive_backup_encryption_key(&root);
        // Generated by the Python one-liner above:
        let expected = hex32("327eae6160f3a0ff6e37d823b9d79f01f1953c501cf1fd7b7494bfed29228395");
        assert_eq!(
            aes_key, expected,
            "derived key differs from Python encryptionloop output"
        );
    }

    fn hex32(s: &str) -> [u8; 32] {
        let mut out = [0u8; 32];
        for i in 0..32 {
            out[i] = u8::from_str_radix(&s[i * 2..i * 2 + 2], 16).unwrap();
        }
        out
    }
}
